config/routes.rb
Final::Application.routes.draw do
  root to: "home#index", as: :home
  devise_for :users
  resources :users
  resources :posts do
    resources :ratings
    end
      resources :posts do
        resources :comments
      end
    
  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	#attr_accessor :content, :name, :tag_list
	acts_as_taggable_on :tags
	has_attached_file :image, :styles => { :medium => "150x150>", :thumb => "60x60>" }, 
	:default_url => "/images/default_:style_avatar.png"
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
    	posts_path
  	end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	layout 'spots'
	def new
		@post = Post.find(params[:post_id])
	    @comment = @post.comments.new
	    @comments = Post.find(params[:post_id]).comments
	end
	def create
		@comment = Comment.new(comment_params)
		@comment.post_id = params[:post_id]
		@comment.user = current_user
			if @comment && @comment.save
			flash[:notice] = 'Your comment has been saved!'
		else
			flash[:alert] = 'There was a problem saving your comment :('
		end
		redirect_to :back
	end
	private
	def comment_params
		params.require(:comment).permit(:review)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	layout 'spots'
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])		
		@comments = Post.find(params[:id]).comments
	end
	def new 
		@post = Post.new
	end
	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if @post && @post.save
			flash[:notice] = 'Your post has been saved'
		else
			flash[:alert] = 'There was a problem saving your post :('
			
		end
		redirect_to posts_path
	end
	private
	def post_params
		params.require(:post).permit(:location, :notes, :image)
	end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
before_filter :set_post
	def create
		@rating = @post.ratings.new :value => params[:value]
		if @rating && @rating.save
			flash[:notice] = 'Your rating was saved successfully'
		else
			flash[:alert] = 'There was a problem saving your rating :('
		end
		redirect_to posts_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout 'account'
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if 	@user.update_attributes(user_params)
			flash[:notice] = 'Your account has been updated'
		else
			flash[:alert] = 'There was a problem saving your account :('
		end
		redirect_to user_path(current_user)
	end
	private
	def user_params
		params.require(:user).permit(:email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<%=image_tag @post.image.url%><br>

<div id='single_comment'%>
	<%@comments.each do |comment|%>
	<%=comment.review%><br>
	<i><%=comment.user.email%></i>
</div>
	<br>
<%end%>
<%=link_to 'All Posts', posts_path%>

app/views/comments/new.html.erb
<div id='posts_show_links'>
	<nav>
			<ul>
				<li>
					<%=link_to 'My Account', user_path(current_user)%>
				</li>
				<li>
					<%=link_to 'View BladerSpots', posts_path%>
				</li>
				<li>
					<%=link_to 'Create New Spot', new_post_path%>
				</li>
				<li>
					<%=link_to 'Sign Out', destroy_user_session_path, method: :delete%>
				</li>
			</ul>
		</nav>
</div>
<h1 id='h1_show'>
<%=@post.location%>
</h1>
<div id='single_post'>
Notes: <%=@post.notes%>
<br>
<%=@post.best_at%>
<%=image_tag @post.image.url, size: '400x400'%>
<br>
Spotted By: <%=@post.user.email%>
<br>
</div>
<div id ='show_comments'>
	<%@comments.each do |comment|%>
	<div id='single_comment'>
		<i><%=comment.user.email%></i>: <%=comment.review%><br>
	</div>
	<%end%>
</div>
<div id = 'new_comment_form'>
<%=simple_form_for [@post,@comment] do |f|%>
	<%=f.input :review, :label => 'Comment'%>
	<%=f.button :submit, :label => 'Post Comment' %>
<%end%>
</div>

app/views/home/index.html.erb
<div id='account_already'>
	Have an account already? <%=link_to 'Sign In', new_user_session_path%>
</div>
<div id='sign_up_image'>
	<%=image_tag 'sign_up.png'%>
</div>
<div id='yes_or_no'>
	<button id='yes'>
		<a href="/users/sign_up">
			Yes
		</a>
	</button>
	<button id='no'>
		<a href="/users/sign_up">
			No
		</a>
	</button>
	<p>
		Either way, create an account !
	</p>
</div>

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	Final
  </title>
  <%= stylesheet_link_tag    "account", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%=image_tag 'banner.png'%>
	</header>
		
<div class="notice">
	<%= notice %>
</div>
<div class="alert">
	<%= alert %>
</div>

<%= yield %>
<footer>
BladerSpot
</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<header>
	<%=image_tag 'banner.png'%>
</header>
<body>
<p class="notice">
	<%= notice %>
</p>
<p class="alert">
	<%= alert %>
</p>
<%= yield %>
<footer>
BladerSpot
</footer>
</body>
</html>

app/views/layouts/comments.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	Final
  </title>
  <%= stylesheet_link_tag    "comments", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%=image_tag 'banner.png'%>
	</header>
		
<div class="notice">
	<%= notice %>
</div>
<div class="alert">
	<%= alert %>
</div>

<%= yield %>
<footer>
BladerSpot
</footer>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
  </script>
  <%= stylesheet_link_tag    "home", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%=image_tag 'banner.png'%>
	</header>
<div class="notice">
	<%= notice %>
</div>
<div class="alert">
	<%= alert %>
</div>
<%= yield %>

</body>
</html>

app/views/layouts/spots.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    "spots", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="notice">
	<%= notice %>
</div>
<div class="alert">
	<%= alert %>
</div>
<%= yield %>
<footer>
BladerSpot
</footer>
</body>
</html>

app/views/posts/index.html.erb
<div id='posts_index_links'>
	<%=link_to 'My Posts', user_path(current_user)%><br>
	<%=link_to 'Log Out',destroy_user_session_path, method: :delete%>
</div>
<div id='upload'>
	<b><%=link_to 'Upload New Spot',new_post_path%></b><br>
</div>

<div id='post_index_posts'>
	<%@posts.reverse_each do |post|%>
<%=link_to post_path(post) do %>
<%=image_tag post.image.url, size: '100x100'%>
<%end%>
<%end%>
<br>
</div>

app/views/posts/new.html.erb
<h1>Create a new post</h1>
<div id='new_post_form'>
	<%=simple_form_for @post do |f|%>
		<%=f.input :location%>
		<%=f.input :notes%>
		<%=f.input :best_at, :label => 'Best time of Day'%>
		<%=f.input :image%>
		<%=f.button :submit%>
	<%end%>
</div>
<div id='posts_new_links'>
	<%=link_to 'View BladerSpots', posts_path%><br>
	<%=link_to 'My Account', user_path(current_user)%>
</div>

app/views/posts/show.html.erb
<div id='posts_show_links'>
	<nav>
			<ul>
				<li>
					<%=link_to 'My Account', user_path(current_user)%>
				</li>
				<li>
					<%=link_to 'View BladerSpots', posts_path%>
				</li>
				<li>
					<%=link_to 'Create New Spot', new_post_path%>
				</li>
				<li>
					<%=link_to 'Sign Out', destroy_user_session_path, method: :delete%>
				</li>
			</ul>
		</nav>
</div>
<h1 id='h1_show'>
<%=@post.location%>
</h1>
<div id='single_post'>
Notes: <%=@post.notes%>
<br>
<%=@post.best_at%>
<%=image_tag @post.image.url, size: '400x400'%>
<br>
Spotted By: <%=@post.user.email%>
<br>
</div>
<div id='show_comments'>
<%@comments.each do |comment|%>
	<div id='single_comment'>
		<i><%=comment.user.email%></i>: <%=comment.review%>
	<br>
</div>
<%end%><br>
<div id='comment_link'>
	<%=link_to 'Comment', new_post_comment_path(@post)%>
</div>
</div>
<br>
</div>

app/views/users/edit.html.erb
<div id='edit_user'>
<%=simple_form_for @user do |f|%>
	<%=f.input :email%>
	<%=f.button :submit%>


<%end%>
</div>

app/views/users/show.html.erb
<div id='user_info'>
	<div id='welcome'>
		<h1>
			Welcome Blader!
		</h1>
	</div>
	<div id='users_show_links'>
		<nav>
			<ul>
				<li>
					<%=link_to 'Edit My Account', edit_user_path(current_user)%>
				</li>
				<li>
					<%=link_to 'View BladerSpots', posts_path%>
				</li>
				<li>
					<%=link_to 'Create New Spot', new_post_path%>
				</li>
				<li>
					<%=link_to 'Sign Out', destroy_user_session_path, method: :delete %>
				</li>
			</ul>
		</nav>
	</div>
</div>
<div id='user_spots'>
	<h2>Your Spots</h2>
	<%@user.posts.each do |post|%>
		<b>Location:</b>
		<br>
		<%=post.location%>
		<br>
		<%=link_to 'View Post', post_path(post)%>
		<br>
		<br>
	<%end%>
</div>